- name: Create Internet Gateway
  amazon.aws.ec2_vpc_igw:
      vpc_id: "{{ ansible_vpc.vpc.id }}"
      region: "{{ region }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      tags:
        Name: "igw"
  register: ansible_igw