- name: create instance
  amazon.aws.ec2_instance:
    name: "ansible-instance"
    key_name: "sample"
    instance_type: t2.micro
    image_id: ami-0c7217cdde317cfec 
    region: "{{ region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    security_group: "{{ security_group.group_id }}"
    vpc_subnet_id: "{{ public_subnet.subnet.id }}"
    wait: yes
    network:
      assign_public_ip: yes
    tags:
      Environment: Development