---
 - name: Create key pair
   amazon.aws.ec2_key:
      name: sample
      region: "{{ region }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
   register: keyout

 - name: Save private key
   copy:
      content: "{{ keyout.key.private_key }}"
      dest: "./sample.pem"
      mode: '0600'
   when: keyout.changed