- name: Create routing table
  amazon.aws.ec2_vpc_route_table:
      vpc_id: "{{ ansible_vpc.vpc.id }}"
      region: "{{ region }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      tags:
        Name: "Public Route Table"
      subnets:
          - "{{ public_subnet.subnet.id }}"
      routes:
          - dest: "0.0.0.0/0"
            gateway_id: "{{ ansible_igw.gateway_id }}"
  register: public_route_table